package exception.customException;

public class MembershipTest {

    public static void main(String[] args) {

        Membership membership = new Membership();
        membership.register(16);

        System.out.println("uygulama çalışmaya devam ediyor");
    }
}
